echo Building Server...
g++ Server.cpp DiffieHellman.cpp fastmodexpon.cpp RSA.cpp SDES.cpp -o server.out
echo Building Client...
g++ Client.cpp DiffieHellman.cpp fastmodexpon.cpp RSA.cpp SDES.cpp -o client.out
echo Done