echo Building Server...
g++ Server.cpp DiffieHellmanRSA.cpp fastmodexpon.cpp RSA.cpp SDES.cpp -o server.out
echo Building Client...
g++ Client.cpp DiffieHellmanRSA.cpp fastmodexpon.cpp RSA.cpp SDES.cpp -o client.out
echo Done